In [1]:
import pandas as pd
import numpy as np

In [2]:
filename = "Friedman_pair.xlsx"
file_addr = "./HCI_Data/ANOVA_SPSS_median/"
result_addr = "./HCI_Data/result/"

In [3]:
df = pd.read_excel(file_addr+filename, engine='openpyxl')


row_names =[
"total_log",
"Input_Stream__(C+IF+INF+F)",
"Fix__(F)",
"Incorrect_Fixed__(IF)",
"Incorrect_Not_Fixed__(INF)",
"All_Actions__(shift, 한영, 특수문자)",
"Input_Stream_with_all_actions__(ISø)",
"total_time__(Seconds)",
"Transcripted_text__(T)",
"Word_per_second__(WPS)",
"Word_per_minute__WPM)",
"AdjWPS",
"AdjWPM",
"Character_per_second__(CPS)",
"Keystrokes_per_second__(KSPS)",
"Gesture_per_second_(GPS)",
"average_intercharacter_time",
"median_intercharacter_time",
"min_intercharacter_time",
"max_intercharacter_time",
"Keystrokes_per_character__(KSPC)",
"Gesture_per_character__(GPC)",
"Minimum_string_distance__(MSD)",
"Corrected_error_rates",
"Uncorrected_error_rates",
"Total_error_rates",
"Utilized_bandwidth",
"Wasted_bandwidth",
"Cost_per_correction",
]
column_names =["Friedman’s Test (P<0.05)", "Wilcoxon signed-rank test (0-0.03)", "Wilcoxon signed-rank test (0-0.08)", "Wilcoxon signed-rank test (0.03-0.08)"]

In [4]:
df.head(50)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,비모수 검정,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,노트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,작성된 출력결과,NaN,06-AUG-2022 00:27:25,NaN,NaN,NaN,NaN,NaN,NaN
4,주석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,입력,데이터,C:\Users\qwqw3\Desktop\HCI_Data\ANOVA_median.sav,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,활성 데이터 세트,데이터세트2,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,필터,<없음>,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,가중,<없음>,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,분할 파일,<없음>,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,작업 데이터 파일의 행 수,40,NaN,NaN,NaN,NaN,NaN,NaN
11,결측값 처리,결측값 정의,사용자 정의 결측값은 누락된 데이터로 처리됩니다.,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,사용 케이스,각 검정에 대한 통계량은 해당 검정에 사용된 변수에 대한 유효 데이터를 포함하는 모...,NaN,NaN,NaN,NaN,NaN,NaN
13,명령문,NaN,NPAR TESTS\n /WILCOXON=total_count_0 total_co...,NaN,NaN,NaN,NaN,NaN,NaN
14,자원,프로세서 시간,00:00:00.02,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,경과 시간,00:00:00.00,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,허용된 케이스의 수a,393216,NaN,NaN,NaN,NaN,NaN,NaN
17,a. 작업 공간 메모리의 가용성을 기준으로.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,기술통계량,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,N,평균,표준편차,최소값,최대값,백분위수,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,25,50 (중위수),75.0
22,total_count_0,40,62.275,7.157522,54,90,57,61,65.0
23,total_count_0.03,40,62.775,6.399068,55,81,57,61.5,67.0
24,total_count_0.09,40,67.25,10.502137,47,93,61,65,75.0
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Wilcoxon 부호순위 검정,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,순위,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,N,평균 순위,순위합,NaN,NaN,NaN,NaN
31,total_count_0.03 - total_count_0,음의 순위,15a,17.233333,258.5,NaN,NaN,NaN,NaN
32,NaN,양의 순위,20b,18.575,371.5,NaN,NaN,NaN,NaN
33,NaN,등순위,5c,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,전체,40,NaN,NaN,NaN,NaN,NaN,NaN
35,total_count_0.09 - total_count_0,음의 순위,10d,16.75,167.5,NaN,NaN,NaN,NaN
36,NaN,양의 순위,29e,21.12069,612.5,NaN,NaN,NaN,NaN
37,NaN,등순위,1f,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,전체,40,NaN,NaN,NaN,NaN,NaN,NaN
39,total_count_0.09 - total_count_0.03,음의 순위,12g,11.916667,143,NaN,NaN,NaN,NaN
40,NaN,양의 순위,23h,21.173913,487,NaN,NaN,NaN,NaN
41,NaN,등순위,5i,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,전체,40,NaN,NaN,NaN,NaN,NaN,NaN
43,a. total_count_0.03 < total_count_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,b. total_count_0.03 > total_count_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,c. total_count_0.03 = total_count_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,d. total_count_0.09 < total_count_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,e. total_count_0.09 > total_count_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,f. total_count_0.09 = total_count_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,g. total_count_0.09 < total_count_0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

con_friedman = df[df.iloc[:,0] == "검정 통계량a"]

friedman_index=[]
for i in con_friedman.index:
    friedman_index.append(i+3)
# print(friedman_index)
friedman_table = pd.DataFrame(index= friedman_index)
for i in friedman_index:
    friedman_table.loc[i,0]= df.iloc[i,1]
    friedman_table.loc[i,1]= df.iloc[i,2]
    friedman_table.loc[i,2]= df.iloc[i,3]
friedman_table = friedman_table.reset_index().drop("index", axis=1)
print(friedman_table)



friedman_table.to_excel(result_addr+"median"+filename)

           0             1         2
0   0.353176  1.876489e-03  0.004737
1   0.294942  1.095696e-04  0.000199
2   0.294571  3.013727e-04  0.000645
3   0.294571  3.013727e-04  0.000645
4   0.063318  1.734969e-02  0.073766
5   0.216367  5.703081e-02  0.114129
6   0.202928  8.640194e-05  0.000376
7   0.019347  9.291771e-07  0.000159
8   0.659695  1.044633e-02  0.010619
9   0.025664  1.494390e-06  0.000037
10  0.025664  1.494390e-06  0.000037
11  0.023112  8.675900e-07  0.000013
12  0.023112  8.675900e-07  0.000013
13  0.025664  1.494390e-06  0.000037
14  0.187756  3.258447e-02  0.146596
15  0.333158  2.393706e-02  0.103865
16  0.128796  5.521265e-05  0.002845
17  0.834951  4.666182e-02  0.052888
18  0.045526  3.310518e-01  0.485206
19  0.026566  3.536861e-03  0.114251
20  0.135519  5.888475e-05  0.000254
21  0.043201  8.550310e-05  0.001960
22  0.067889  1.775592e-02  0.075304
23  0.258345  4.143262e-04  0.001615
24  0.067889  1.796048e-02  0.066316
25  0.258361  8.744579e-05  0.000157
26  0.274832  1.536198e-04  0.000225
27  0.274832  1.536198e-04  0.000225
28  0.360237  3.201275e-04  0.000444